In [1]:
import torch
import numpy as np
from datasets.openml_datasets import OpenML_Dataset

from utils.weakener import Weakener
from models.model import MLP
from utils.losses import PartialLoss,LBLoss,EMLoss,OSLCELoss,OSLBrierLoss
from utils.trainig_testing import train_model,evaluate_model,train_and_evaluate


In [2]:
Data = OpenML_Dataset('iris')
train_x, train_y, test_x, test_y = Data.get_data()

In [3]:
Weak = Weakener(Data.num_classes)
Weak.generate_M(model_class='pll')

In [4]:
Weak.M,Weak.Z

(array([[0.   , 0.375, 0.375],
        [0.375, 0.   , 0.375],
        [0.375, 0.375, 0.   ],
        [0.25 , 0.25 , 0.25 ]]),
 array([[0, 1, 1],
        [1, 0, 1],
        [1, 1, 0],
        [1, 1, 1]]))

In [5]:
z,w = Weak.generate_weak(train_y)

In [6]:
train_y[:5,:],z[:5],w[:5,:]

(tensor([[0., 0., 1.],
         [0., 1., 0.],
         [0., 0., 1.],
         [0., 1., 0.],
         [1., 0., 0.]]),
 tensor([0, 3, 1, 2, 1], dtype=torch.int32),
 tensor([[0., 1., 1.],
         [1., 1., 1.],
         [1., 0., 1.],
         [1., 1., 0.],
         [1., 0., 1.]], dtype=torch.float64))

In [8]:
Weak.generate_wl_priors()

array([0.26644739, 0.23684204, 0.24671057, 0.25      ])

In [7]:
#Nothing changed